-- MySQL Script generated by MySQL Workbench
-- Wed Aug 16 10:36:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carpoolproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carpoolproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carpoolproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `carpoolproject` ;

-- -----------------------------------------------------
-- Table `carpoolproject`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carpoolproject`.`role` ;

CREATE TABLE IF NOT EXISTS `carpoolproject`.`role` (
  `id` INT NOT NULL DEFAULT '1000',
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carpoolproject`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carpoolproject`.`user` ;

CREATE TABLE IF NOT EXISTS `carpoolproject`.`user` (
  `id` INT NOT NULL,
  `roll_id` INT NOT NULL,
  `login_id` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `roll_fk_idx` (`roll_id` ASC) VISIBLE,
  CONSTRAINT `roll_fk`
    FOREIGN KEY (`roll_id`)
    REFERENCES `carpoolproject`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carpoolproject`.`vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carpoolproject`.`vehicle` ;

CREATE TABLE IF NOT EXISTS `carpoolproject`.`vehicle` (
  `id` INT NOT NULL,
  `cid` INT NOT NULL,
  `model` VARCHAR(200) NOT NULL,
  `year` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `Licence` VARCHAR(45) NOT NULL,
  `rc_book` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_fk_idx` (`cid` ASC) VISIBLE,
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`cid`)
    REFERENCES `carpoolproject`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carpoolproject`.`ride`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carpoolproject`.`ride` ;

CREATE TABLE IF NOT EXISTS `carpoolproject`.`ride` (
  `id` INT NOT NULL,
  `cid` INT NOT NULL,
  `start_location` VARCHAR(200) NOT NULL,
  `End_location` VARCHAR(200) NOT NULL,
  `vid` INT NOT NULL,
  `time_and _date_of_departure` DATETIME NOT NULL,
  `time_of_arival` DATETIME NOT NULL,
  `price_per_seat` INT NOT NULL,
  `Available_seats` INT NOT NULL,
  `status` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_cidfk_idx` (`cid` ASC) VISIBLE,
  CONSTRAINT `user_cidfk`
    FOREIGN KEY (`cid`)
    REFERENCES `carpoolproject`.`user` (`id`),
  CONSTRAINT `vid_fk`
    FOREIGN KEY (`id`)
    REFERENCES `carpoolproject`.`vehicle` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carpoolproject`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carpoolproject`.`booking` ;

CREATE TABLE IF NOT EXISTS `carpoolproject`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pid` INT NOT NULL,
  `rid` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `no_of_seats` INT NOT NULL,
  `total_price` INT NOT NULL,
  `status` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_pidfk_idx` (`pid` ASC) VISIBLE,
  INDEX `rid_fk_idx` (`rid` ASC) VISIBLE,
  CONSTRAINT `rid_fk`
    FOREIGN KEY (`rid`)
    REFERENCES `carpoolproject`.`ride` (`id`),
  CONSTRAINT `user_pidfk`
    FOREIGN KEY (`pid`)
    REFERENCES `carpoolproject`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carpoolproject`.`carowner_passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carpoolproject`.`carowner_passenger` ;

CREATE TABLE IF NOT EXISTS `carpoolproject`.`carowner_passenger` (
  `id` INT NOT NULL DEFAULT '100',
  `user_id` INT NOT NULL,
  `aadhar_no` VARCHAR(45) NOT NULL,
  `driving_licence` VARCHAR(45) NULL DEFAULT NULL,
  `fname` VARCHAR(100) NOT NULL,
  `lname` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `phone_no` VARCHAR(45) NOT NULL,
  `primary_email` VARCHAR(100) NOT NULL,
  `secondary_email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `uid_fk_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `uid_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `carpoolproject`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carpoolproject`.`co_passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carpoolproject`.`co_passenger` ;

CREATE TABLE IF NOT EXISTS `carpoolproject`.`co_passenger` (
  `id` INT NOT NULL,
  `pid` INT NOT NULL,
  `aadhar_no` VARCHAR(45) NULL DEFAULT NULL,
  `phone_no` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pidfk_idx` (`pid` ASC) VISIBLE,
  CONSTRAINT `pidfk`
    FOREIGN KEY (`pid`)
    REFERENCES `carpoolproject`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carpoolproject`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carpoolproject`.`payment` ;

CREATE TABLE IF NOT EXISTS `carpoolproject`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bid` INT NOT NULL,
  `cid` INT NOT NULL,
  `pid` INT NOT NULL,
  `amount` INT NOT NULL,
  `Date_time` DATETIME NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_cidfk_idx` (`cid` ASC) VISIBLE,
  INDEX `bid_fk_idx` (`bid` ASC) VISIBLE,
  CONSTRAINT `bid_fk`
    FOREIGN KEY (`bid`)
    REFERENCES `carpoolproject`.`booking` (`id`),
  CONSTRAINT `user_cid1fk`
    FOREIGN KEY (`cid`)
    REFERENCES `carpoolproject`.`user` (`id`),
  CONSTRAINT `user_pid1fk`
    FOREIGN KEY (`cid`)
    REFERENCES `carpoolproject`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `carpoolproject`;

DELIMITER $$

USE `carpoolproject`$$
DROP TRIGGER IF EXISTS `carpoolproject`.`booking_BEFORE_INSERT` $$
USE `carpoolproject`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `carpoolproject`.`booking_BEFORE_INSERT`
BEFORE INSERT ON `carpoolproject`.`booking`
FOR EACH ROW
BEGIN

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
